#.yml的语法如下。
#！！！！！！！！！每一个冒号后面都有一个空格，别问为什么，语法就是这样！不然疯狂报错！切记。
#还有，比如下方jdbc:mysql://localhost:3306这些冒号后面不需要空格，加了会报错。
server:
   port: 8080
   session-timeout: 30
   tomcat.max-threads: 0
   tomcat.uri-encoding: UTF-8

spring:
   datasource:
       url : jdbc:mysql://localhost:3306/booksystem?characterEncoding=UTF-8
       username: root
       password: root
       driverClassName: com.mysql.jdbc.Driver
   mvc:
     view:
        prefix: /
        suffix: .jsp
   
mybatis:
       type-aliases-package: com.ltc.pojo
       mapper-locations: classpath*:/mybaits/*.xml